sonar.organization=uris-tim5
sonar.projectKey=uris-tim5-project
sonar.projectName=URIS Tim 5 Project
sonar.sources=backend,frontend/src
sonar.tests=backend
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/bin/**,**/obj/**,**/migrations/**,frontend/node_modules/**,**/._*
